name: AVIF compression of GIFs

on:
  workflow_dispatch:
  workflow_call:

jobs:
  avif_gif_compress:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          
      - name: Install FFMPEG
        shell: pwsh
        run: |
          sudo apt update
          sudo apt install ffmpeg
          sudo apt install libavif-bin
      
      - name: Compress images and measure times
        shell: pwsh
        run: |
          # only input gifs
          $inputFiles = gci ./inputs/ -File | Where { $_.Name -like "*.gif" }
          mkdir ./outputs/
          $sw = [System.Diagnostics.Stopwatch]::new()
          # careful: don't use $input as variable in PowerShell (forbidden name)
          foreach ($inputFile in $inputFiles)
          {
            $fileNameWithoutExtension = $($inputFile.Name.ToLower().Replace(".jpg","").Replace(".png","").Replace(".gif",""))
            $outputFilePath = "./outputs/${fileNameWithoutExtension}.avif"
            $sw.Restart()
            # https://codelabs.developers.google.com/codelabs/avif#5
            ffmpeg -i $inputFile.FullName -pix_fmt yuv420p -f yuv4mpegpipe "${fileNameWithoutExtension}.y4m"
            avifenc "${fileNameWithoutExtension}.y4m" $outputFilePath
            $sw.Stop()

            $elapsedTimeInSeconds = [math]::ceiling($sw.ElapsedMilliseconds)
            # changing the name of output file to hold elapsed milliseconds
            Rename-Item $outputFilePath "${fileNameWithoutExtension}.${elapsedTimeInSeconds}ms.avif"
          }

      - name: Upload to workflow results
        uses: actions/upload-artifact@v4
        with:
          compression-level: 0 # no need to compress because AVIF already compressed
          name: avif_gif_results
          path: ./outputs/
