name: AVIF compression of static images

on:
  workflow_dispatch:
  workflow_call:

jobs:
  avif_static_compress:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Download cavif-rs
        shell: pwsh
        run: |
          $url = "https://github.com/kornelski/cavif-rs/releases/download/v1.5.5/cavif-1.5.5.zip"
          $destinationFile = "cavif.zip"
          Invoke-WebRequest -Uri $url -OutFile $destinationFile
          mkdir libcavif
          unzip cavif.zip -d ./libcavif/
      
      - name: Compress images and measure times
        shell: pwsh
        run: |
          # all input images except gifs, because cavif-rs can't handle gifs yet
          $inputFiles = gci ./inputs/ -File | Where { $_.Name -notlike "*.gif" }
          $resultsFile = "./outputs/avif_static_results.txt"
          mkdir ./outputs/
          ni $resultsFile
          $sw = [System.Diagnostics.Stopwatch]::new()
          # careful: don't use $input as variable in PowerShell (forbidden name)
          foreach ($inputFile in $inputFiles)
          {
            $fileNameWithoutExtension = $($inputFile.Name.ToLower().Replace(".jpg","").Replace(".png","").Replace(".gif",""))
            $outputFilePath = "./outputs/${fileNameWithoutExtension}.avif"
            $sw.Restart()
            ./libcavif/linux-generic/cavif $inputFile.FullName -o $outputFilePath -Q 90 -f
            $sw.Stop()
            
            $inputFileSize = [math]::ceiling($inputFile.Length / 1KB)
            $outputFileSize = [math]::ceiling((Get-Item $outputFilePath).Length / 1KB)
            $compressionRatio = [math]::floor(($outputFileSize / $inputFileSize) * 100) - 100
            $elapsedTimeInSeconds = [math]::ceiling($sw.Elapsed.TotalSeconds)
            echo "| $($inputFile.Name) | $($inputFileSize)KB | ${fileNameWithoutExtension}.avif | $($outputFileSize)KB | $($compressionRatio)% | $($elapsedTimeInSeconds)s |" >> $resultsFile
          }

      - name: Upload to workflow results
        uses: actions/upload-artifact@v4
        with:
          compression-level: 0 # no need to compress because AVIF already compressed
          name: avif_static_results
          path: ./outputs/
