name: AVIF compression of static images

on:
  workflow_call:
    inputs:
      cavif_version:
        required: true
        type: string
      quality_factor:
        required: true
        type: string

jobs:
  avif_static_compress:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          
      - name: Download cavif-rs
        shell: pwsh
        run: |
          $url = "https://github.com/kornelski/cavif-rs/releases/download/v${env:CAVIF_VERSION}/cavif-${env:CAVIF_VERSION}.zip"
          $destinationFile = "cavif.zip"
          Invoke-WebRequest -Uri $url -OutFile $destinationFile
          mkdir libcavif
          unzip cavif.zip -d ./libcavif/
        env:
          CAVIF_VERSION: ${{ inputs.cavif_version }}
      
      - name: Compress images and measure times
        shell: pwsh
        run: |
          # all input images except gifs, because cavif-rs can't handle gifs yet
          $inputFiles = gci ./inputs/ -File | Where { $_.Name -notlike "*.gif" }
          mkdir ./outputs/
          $sw = [System.Diagnostics.Stopwatch]::new()
          # careful: don't use $input as variable in PowerShell (forbidden name)
          foreach ($inputFile in $inputFiles)
          {
            $fileNameWithoutExtension = $($inputFile.Name.ToLower().Replace(".jpg","").Replace(".png","").Replace(".gif",""))
            $outputFilePath = "./outputs/${fileNameWithoutExtension}.avif"
            $sw.Restart()
            ./libcavif/linux-generic/cavif $inputFile.FullName -o $outputFilePath -Q $env:QUALITY_FACTOR -f
            $sw.Stop()
            
            $elapsedTimeInSeconds = [math]::ceiling($sw.ElapsedMilliseconds)
            # changing the name of output file to hold elapsed milliseconds
            Rename-Item $outputFilePath "${fileNameWithoutExtension}.${elapsedTimeInSeconds}ms.avif"
          }
        env:
          QUALITY_FACTOR: ${{ inputs.quality_factor }}

      - name: Upload to workflow results
        uses: actions/upload-artifact@v4
        with:
          compression-level: 0 # no need to compress because AVIF already compressed
          name: avif_static_results
          path: ./outputs/
