name: JXL and AVIF benchmark

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  jxl_compression:
    uses: ./.github/workflows/jxl_compress.yml
  
  avif_static_compression:
    uses: ./.github/workflows/avif_static_compress.yml
  
  avif_gif_compression:
    uses: ./.github/workflows/avif_gif_compress.yml

  make_results_table:
    needs: [jxl_compression, avif_static_compression, avif_gif_compression]
    uses: ./.github/workflows/make_results_table.yml
