name: JXL and AVIF benchmark

on:
  workflow_dispatch:
    inputs:
      libjxl_version:
        description: 'libjxl release version'
        required: true
        default: '0.12.0'
        type: string
      #libjxl_quality_factor:
      #  description: 'JXL quality factor (100 is lossless)'
      #  required: true
      #  default: 90
      #  type: number
      libavif_version:
        description: 'libavif release version'
        required: true
        default: '1.4.2'
        type: string
      #libavif_quality_factor:
      #  description: 'AVIF quality factor (100 is not lossless, dont use it)'
      #  required: true
      #  default: 90
      #  type: number
  push:
    branches:
      - master

jobs:
  jxl_compression:
    uses: ./.github/workflows/jxl_compress.yml
    with:
      libjxl_version: ${{ inputs.libjxl_version || '0.12.0' }}
      #quality_factor: ${{ inputs.libjxl_quality_factor || '90' }}
  
  avif_compression:
    uses: ./.github/workflows/avif_compress.yml
    with:
      libavif_version: ${{ inputs.libavif_version || '1.4.2' }}
      #quality_factor: ${{ inputs.libavif_quality_factor || '90' }}

  make_results_table:
    needs: [jxl_compression, avif_compression]
    uses: ./.github/workflows/make_results_table.yml
    with:
      libjxl_version: ${{ inputs.libjxl_version || '0.12.0' }}
      #libjxl_quality_factor: ${{ inputs.libjxl_quality_factor || '90' }}
      libavif_version: ${{ inputs.libavif_version || '1.4.2' }}
      #libavif_quality_factor: ${{ inputs.libavif_quality_factor || '90' }}
